name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    env: 
      endpoint: ${{ secrets.ALIYUN_ENDPOINT }}
      uname: ${{ secrets.ALIYUN_USERNAME }}
      pwd: ${{ secrets.ALIYUN_PWD }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      id: build
      run: docker build . --file Dockerfile --tag nginx:latest
    - name: Login to Aliyun
      run: docker login --username=$uname $endpoint -p $pwd
    - name: Tag
      run: docker tag nginx:latest $endpoint/yunwu-docker/nginx:latest-actions
    - name: Push
      run: docker push $endpoint/yunwu-docker/nginx:latest-actions

